baseurl = "http://docs.getcloudify.org/"
languageCode = "en-us"
title = "Cloudify Documentation"
theme="hugo-bootswatch"
uglyurls=false

[blackfriday]
plainIdAnchors=true

[params]
highlightStyle="darkula"
projecturl="https://github.com/cloudify-cosmo/docs.getcloudify.org"
projectversion="master"
# this is where you type google analytics ID
googleAnalytics="UA-31930048-1"
# this is where you decide where "/" redirects to
homepage="/intro/what-is-cloudify/"

# this is where you control the top menu
[[menu.main]]
    name = "intro"
    weight = -110
    identifier = "intro"
    url = "/intro/what-is-cloudify"

[[menu.main]]
    name = "docs"
    weight = -100
    [[menu.main]]
        name = "3.3"
        parent = "docs"
        weight = 0
        url = "/installation/prerequisites"
    [[menu.main]]
        name = "3.2"
        parent = "docs"
        weight = 1
        url = "http://getcloudify.org/guide/3.2/quickstart.html"
    [[menu.main]]
        name = "3.1"
        parent = "docs"
        weight = 2
        url = "http://getcloudify.org/guide/3.1/quickstart.html"

[[menu.main]]
    name = "product"
    weight = -90
    [[menu.main]]
        name = "download cloudify"
        parent = "product"
        weight = 0
        url = "http://getcloudify.org/downloads/get_cloudify_3x.html"
    [[menu.main]]
        name = "about cloudify"
        parent = "product"
        weight = 1
        url = "http://getcloudify.org/cloud_orchestration_cloud_automation.html"
    [[menu.main]]
        name = "how it works"
        parent = "product"
        weight = 2
        url = "http://getcloudify.org/how-it-works.html"
    [[menu.main]]
        name = "cloudify roadmap"
        parent = "product"
        weight = 3
        url = "http://getcloudify.org/cloudify-roadmap.html"
    [[menu.main]]
        name = "code examples"
        parent = "product"
        weight = 4
        url = "http://getcloudify.org/examples/home.html"

[[menu.main]]
    name = "resources"
    weight = -80
    [[menu.main]]
        name = "videos & tutorials"
        parent = "resources"
        weight = 0
        url = "http://getcloudify.org/cloudifysourcetv.html"
    [[menu.main]]
        name = "events"
        parent = "resources"
        weight = 1
        url = "http://getcloudify.org/participate.htm"
    [[menu.main]]
        name = "cloudify tumblr"
        parent = "resources"
        weight = 2
        url = "http://cloudifysource.tumblr.com/"
    [[menu.main]]
        name = "faq"
        parent = "resources"
        weight = 3
        url = "http://getcloudify.org/FAQ_cloud_devops_automation.html"
    [[menu.main]]
        name = "careers"
        parent = "resources"
        weight = 4
        url = "http://jobs.gigaspaces.com"
[[menu.main]]
    name = "blog"
    weight = -70
    url = "http://getcloudify.org/blog"
[[menu.main]]
    name = ".com"
    weight = -60
    pre = "<strong>"
    post = "</strong> <i class='fa fa-external-link-square'></i>"
    url = "http://gigaspaces.com"


# this is where you control the order of sections in intro
# 'identifier' must match the section's directory name
# 'name' is how you want to display the section on screen
# 'weight' sets the order of sections in intro (smaller is higher)
[[menu.intro]]
    identifier = "intro"
    name = "introduction"
    url = "/intro/what-is-cloudify"
    weight = 0

# this is where you control the order of sections in docs
# 'identifier' must match the section's directory name
# 'name' is how you want to display the section on screen
# 'weight' sets the order of sections in docs (smaller is higher)
[[menu.docs]]
    identifier = "intro"
    name = "introduction"
    url = "/intro/what-is-cloudify"
    weight = 0

[[menu.docs]]
  identifier = "installation"
  name = "installation"
  weight = 1

[[menu.docs]]
  identifier = "blueprints"
  name = "blueprints"
  weight = 2

[[menu.docs]]
  identifier = "cli"
  name = "command line interface"
  weight = 3

[[menu.docs]]
  identifier = "workflows"
  name = "workflows"
  weight = 4

[[menu.docs]]
  identifier = "plugins"
  name = "plugins"
  weight = 5

[[menu.docs]]
  identifier = "manager_intro"
  name = "manager introduction"
  weight = 6

[[menu.docs]]
  identifier = "manager_webui"
  name = "manager web interface"
  weight = 7

[[menu.docs]]
  identifier = "agents"
  name = "agents"
  weight = 8

[[menu.docs]]
  identifier = "manager"
  name = "manager"
  weight = 9

[[menu.docs]]
  identifier = "manager_policies"
  name = "manager policies"
  weight = 10

[[menu.docs]]
  identifier = "manager_architecture"
  name = "manager architecture"
  weight = 11

[[menu.docs]]
  identifier = "composer"
  name = "composer"
  weight = 12

[[menu.docs]]
  identifier = "apis"
  name = "APIs"
  weight = 13
